### ISSUE TITLE
401 error on getting token

### ISSUE THREAD

**Issue by novia713** [contentacms/contenta_jsonapi#239]
i have this CORS config:
```
  cors.config:
    enabled: true
    allowedHeaders:
        - '*'
    allowedMethods:
        - '*'
    allowedOrigins:
        - '*'
    exposedHeaders: false
    maxAge: false
    supportsCredentials: false
```

in a vue.js frontend app we try to login with
a `POST https://mydomain.es/oauth/token` call
and we get 
```
401 (Unauthorized)
```

any idea?

obviously, the backend API and the vue.js app are each one in different subdomains
